# Generated by Django 5.0.6 on 2026-04-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itemdata',
            fields=[
                ('is_approved', models.BooleanField(db_column='IS_APPROVED', default=False)),
                ('is_active', models.BooleanField(blank=True, db_column='IS_ACTIVE', default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, db_column='IS_DELETED', default=False, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE')),
                ('last_updated_by', models.CharField(blank=True, db_column='LAST_UPDATED_BY', max_length=50, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE')),
                ('item_id', models.AutoField(db_column='SO_ID', primary_key=True, serialize=False)),
                ('so_number', models.CharField(blank=True, db_column='SO_NUMBER', max_length=20, null=True)),
                ('item_number', models.CharField(db_column='ITEM_NUMBER', max_length=10)),
                ('material_no', models.CharField(db_column='MATERIAL_NO', max_length=10)),
                ('material_qty', models.CharField(db_column='MATERIAL_QTY', max_length=20)),
                ('unit', models.CharField(db_column='UNIT', max_length=20)),
                ('material_price', models.CharField(db_column='MATERIAL_PRICE', max_length=20)),
                ('matl_value', models.CharField(db_column='MATL_VALUE', max_length=20)),
                ('status', models.CharField(db_column='STATUS', default='Active', max_length=80)),
            ],
            options={
                'db_table': 'MST_ITEM_DATA',
            },
        ),
        migrations.CreateModel(
            name='Sodata',
            fields=[
                ('is_approved', models.BooleanField(db_column='IS_APPROVED', default=False)),
                ('is_active', models.BooleanField(blank=True, db_column='IS_ACTIVE', default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, db_column='IS_DELETED', default=False, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE')),
                ('last_updated_by', models.CharField(blank=True, db_column='LAST_UPDATED_BY', max_length=50, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE')),
                ('so_id', models.AutoField(db_column='SO_ID', primary_key=True, serialize=False)),
                ('so_number', models.CharField(db_column='SO_NUMBER', db_index=True, max_length=20, null=True)),
                ('company_code', models.CharField(db_column='COMPANY_CODE', max_length=10)),
                ('plant_code', models.CharField(db_column='PLANT_CODE', max_length=10)),
                ('customer_code', models.CharField(db_column='CUSTOMER_CODE', max_length=20)),
                ('ship_to_party', models.CharField(db_column='SHIP_TO_PARTY', max_length=20)),
                ('ship_to_address', models.CharField(blank=True, db_column='SHIP_TO_ADDRESS', max_length=100, null=True)),
                ('ship_to_city', models.CharField(blank=True, db_column='SHIP_TO_CITY', max_length=50, null=True)),
                ('ship_to_street', models.CharField(blank=True, db_column='SHIP_TO_STREET', max_length=50, null=True)),
                ('ship_to_pincode', models.CharField(blank=True, db_column='SHIP_TO_PINCODE', max_length=50, null=True)),
                ('ship_to_country', models.CharField(blank=True, db_column='SHIP_TO_COUNTRY', max_length=50, null=True)),
                ('so_value', models.DecimalField(db_column='SO_VALUE', decimal_places=2, max_digits=18)),
                ('pyt_terms', models.CharField(db_column='PYT_TERMS', max_length=50)),
                ('remarks', models.CharField(db_column='REMARKS', max_length=200)),
                ('cust_reference', models.CharField(db_column='CUST_REFERENCE', max_length=50)),
                ('cust_reference_date', models.DateField(db_column='CUST_REFERENCE_DATE')),
                ('inco_terms', models.CharField(db_column='INCO_TERMS', max_length=30)),
                ('inco_location', models.CharField(db_column='INCO_LOCATION', max_length=100)),
                ('status', models.CharField(db_column='STATUS', default='Active', max_length=80)),
            ],
            options={
                'db_table': 'MST_SODATA',
            },
        ),
    ]
