# Generated by Django 5.0.6 on 2026-03-05 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
                ('plant_code', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_to_party', models.CharField(blank=True, max_length=100, null=True)),
                ('so_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('special_remark', models.CharField(blank=True, max_length=255, null=True)),
                ('cust_ref_po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_ref_po_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lc_attachments/')),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lc_request',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='LCSODetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(max_length=50)),
                ('interest_free_credit_days', models.IntegerField(blank=True, null=True)),
                ('interest_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usance_period', models.IntegerField(blank=True, null=True)),
                ('lc_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_details', to='lc_request.lcrequest')),
            ],
            options={
                'db_table': 'lc_so_detail',
            },
        ),
    ]
