# Generated by Django 5.0.6 on 2026-04-27 09:11

import django.db.models.deletion
import lc_request.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LcDetails',
            fields=[
                ('status', models.CharField(db_column='STATUS', default='Draft', max_length=100)),
                ('is_approved', models.BooleanField(db_column='IS_APPROVED', default=False)),
                ('is_active', models.BooleanField(blank=True, db_column='IS_ACTIVE', default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, db_column='IS_DELETED', default=False, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE')),
                ('last_updated_by', models.CharField(blank=True, db_column='LAST_UPDATED_BY', max_length=50, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE')),
                ('lc_details_id', models.AutoField(db_column='LC_DETAILS_ID', primary_key=True, serialize=False)),
                ('instrument_number', models.CharField(db_column='INSTRUMENT_NUMBER', max_length=100)),
                ('form_of_doc', models.CharField(blank=True, db_column='FORM_OF_DOC', max_length=100, null=True)),
                ('opening_bank', models.CharField(blank=True, db_column='OPENING_BANK', max_length=200, null=True)),
                ('opening_date', models.DateField(blank=True, db_column='OPENING_DATE', null=True)),
                ('unance_period', models.IntegerField(blank=True, db_column='UNANCE_PERIOD', null=True)),
                ('dispatch_upto_date', models.DateField(blank=True, db_column='DISPATCH_UPTO_DATE', null=True)),
                ('negotiation_days', models.IntegerField(blank=True, db_column='NEGOTIATION_DAYS', null=True)),
                ('expiry_date', models.DateField(blank=True, db_column='EXPIRY_DATE', null=True)),
                ('place_take_in_charge', models.CharField(blank=True, db_column='PLACE_TAKE_IN_CHARGE', max_length=200, null=True)),
                ('place_of_final_destination', models.CharField(blank=True, db_column='PLACE_OF_FINAL_DESTINATION', max_length=200, null=True)),
                ('advising_bank', models.CharField(blank=True, db_column='ADVISING_BANK', max_length=200, null=True)),
                ('es', models.CharField(blank=True, db_column='ES', max_length=10, null=True)),
                ('et', models.CharField(blank=True, db_column='ET', max_length=10, null=True)),
                ('er', models.CharField(blank=True, db_column='ER', max_length=10, null=True)),
                ('grace_value', models.DecimalField(blank=True, db_column='GRACE_VALUE', decimal_places=2, max_digits=15, null=True)),
                ('percentage_credit_amount_tolerance', models.TextField(blank=True, db_column='PERCENTAGE_CREDIT_AMOUNT_TOLERANCE', max_length=20, null=True)),
                ('cust_name_inv_print', models.CharField(blank=True, db_column='CUST_NAME_INV_PRINT', max_length=200, null=True)),
                ('customer_name', models.CharField(blank=True, db_column='CUSTOMER_NAME', max_length=200, null=True)),
                ('clause_45a', models.TextField(blank=True, db_column='CLAUSE_45A', null=True)),
                ('incoterm', models.CharField(blank=True, db_column='INCOTERM', max_length=10, null=True)),
                ('imps_remark', models.TextField(blank=True, db_column='IMPS_REMARK', null=True)),
                ('additional_condition_46a', models.TextField(blank=True, db_column='ADDITIONAL_CONDITION_46A', null=True)),
                ('clause_78', models.TextField(blank=True, db_column='CLAUSE_78', null=True)),
                ('extracted_flag', models.CharField(choices=[('Y', 'Extracted'), ('N', 'User Editable')], db_column='EXTRACTED_FLAG', default='N', max_length=1)),
            ],
            options={
                'db_table': 'TRANS_LC_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='LcFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(db_column='IS_APPROVED', default=False)),
                ('is_active', models.BooleanField(blank=True, db_column='IS_ACTIVE', default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, db_column='IS_DELETED', default=False, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE')),
                ('last_updated_by', models.CharField(blank=True, db_column='LAST_UPDATED_BY', max_length=50, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE')),
                ('file', models.FileField(db_column='FILE', upload_to=lc_request.functions.handle_file_upload_path)),
                ('category', models.CharField(db_column='CATEGORY', max_length=20)),
                ('status', models.CharField(db_column='STATUS', default='active', max_length=50)),
                ('password', models.CharField(blank=True, db_column='PASSWORD', max_length=128, null=True)),
                ('lc_details', models.IntegerField(blank=True, db_column='LC_DETAILS_ID', null=True)),
            ],
            options={
                'db_table': 'TRANS_LC_FILES',
            },
        ),
        migrations.CreateModel(
            name='LcRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_column='STATUS', default='Draft', max_length=100)),
                ('is_approved', models.BooleanField(db_column='IS_APPROVED', default=False)),
                ('is_active', models.BooleanField(blank=True, db_column='IS_ACTIVE', default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, db_column='IS_DELETED', default=False, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE')),
                ('last_updated_by', models.CharField(blank=True, db_column='LAST_UPDATED_BY', max_length=50, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE')),
                ('interest_free_credit_days', models.IntegerField(blank=True, db_column='INTEREST_FREE_CREDIT_DAYS', null=True)),
                ('interest_charges', models.DecimalField(blank=True, db_column='INTEREST_CHARGES', decimal_places=2, max_digits=12, null=True)),
                ('usance_period', models.IntegerField(blank=True, db_column='USANCE_PERIOD', null=True)),
                ('request_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], db_column='REQUEST_STATUS', default='draft', max_length=20)),
                ('lc_details', models.ForeignKey(blank=True, db_column='LC_DETAILS_ID', help_text='Points to the N (user-editable) LcDetails entry.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lc_request_lc_details', to='lc_request.lcdetails')),
                ('so_data', models.ManyToManyField(blank=True, related_name='lc_request_sodata', to='masters.sodata')),
            ],
            options={
                'db_table': 'TRANS_LC_REQUEST',
            },
        ),
    ]
