"""
Django settings for lcpark project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--^ifye!@toqur%-np@e!#@fiv*&5w%q2!4vt4_$8b+1$y77(q6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

DEPENDENCY_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'workflow',
    'rbac',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'reversion',
    'reversion_compare'
]

PROJECT_APPS = ['masters', 'lc_request']

INSTALLED_APPS = DEPENDENCY_APPS + PROJECT_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'approval-authorization',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'req',
    'source'
]

ROOT_URLCONF = 'lcpark.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lcpark.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


USE_SQLITE_AS_DEFAULT = os.getenv("USE_SQLITE_AS_DEFAULT", "false").lower() == "true"

DATABASES = {
    "default": (
        {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
        if USE_SQLITE_AS_DEFAULT
        else {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "LC_PARK",
            "USER": "postgres",
            "PASSWORD": "admin",
            "HOST": "localhost",
            "PORT": "5432",
        }
    ),

    # ✅ keep SQLite explicit as well (optional but useful)
    "sqlite": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}



REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],

    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser'
    ],

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'DEFAULT_METADATA_CLASS': 'api.metadata.MinimalMetadata',

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',

    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    # ],

}
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MODEL_VALIDATORS = {}

DISPLAY_MODELS = {
    'sodata':'Sodata',
    'itemdata':'Itemdata',
}

DISPLAY_MODEL_FIELDS = {
    'sodata': ['so_id','so_number', 'plant_code', 'customer_code', 'ship_to_party', 'so_value', 'pyt_terms', 'remarks', 'cust_reference', 'cust_reference_date', 'inco_terms', 'inco_location', 'status'],
    'itemdata': ['so_id', 'so_number', 'item_number', 'material_no', 'material_qty', 'unit', 'material_price', 'matl_value'],
}

AUTO_GENERATION_SECTIONS = ['MASTERS']

EXTRA_USER_META = {
    'MASTERS': [
        {
            'app': 'masters',
            'model': 'sodata',
            'title': 'SO Data'
        },
        {
            'app': 'masters',
            'model': 'itemdata',
            'title': 'Item Data'
        },
    ],
    'lc_request': [                          # ← this key must match ScreenRouters.js
        {
            'screen': 'lc_request',
            'title': 'LC Request',
            'type': 'subsection',           # ← change from 'subsection' to 'transaction'
        }
    ],
}

SECTION_ICONS = {
    'MASTERS': 'TableOutlined',
    'lc_request': 'CheckCircleOutlined'
}

URL_METADATA_CLASS = {
    'api': 'api.metadata.ApiMetadata',
    'User': 'rbac.metadata.RbacMetadata',
    'Suggest': 'rbac.metadata.RbacMetadata',
    'Group': 'rbac.metadata.RbacMetadata',
    'Permission': 'rbac.metadata.RbacMetadata',
}

MODEL_FIELD_CHOICES = {
}

MASTERS_APP_RBAC = 'masters'


APPLY_SEARCH_MODEL_FIELDS = {
    'sodata': ['so_id','so_number','company_code', 'plant_code', 'customer_code', 'ship_to_party', 'so_value', 'pyt_terms', 'remarks', 'cust_reference', 'cust_reference_date', 'inco_terms', 'inco_location'],
    'itemdata': ['so_id', 'so_number', 'item_number', 'material_no', 'material_qty', 'unit', 'material_price', 'matl_value'],
}


FOREIGN_KEY_UI_NAME_MAP = {
}


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'
X_FRAME_OPTIONS = 'SAMEORIGIN'

WORKFLOW_EMAIL_POLICY = {
    'default': {
        'Init': {
            'request': 'workflow.email_policy.notify_next_level',
        },
        'Approve': {
            'request': 'workflow.email_policy.notify_next_level',
            'notification': 'workflow.email_policy.get_request_initiator'
        },
        'Reject': {
            'notification': 'workflow.email_policy.notify_the_hierarchy'
        },
    }
}

RABBITMQ_CONF = {
    "RABBITMQ_CON_URL": "",
    "RABBITMQ_QUEUE": "",
    "SENDER_MAIL": "",
    "MAIL_CREDENTIALS": {"sender_email": "", "mailserver": ""}
}

WORKFLOW_MAIL_MAP = {

}

MODELS_WITH_MAIL_APPROVAL = []

LANDING_PAGE_FMT = "http://localhost:3000/app/ApprovalForm/{}"

APPROVAL_API_URLS = {
}

# APPROVAL_GROUPS = []

MASTERS_APP_NAME = 'masters'

DATE_INPUT_FORMAT = []

DATE_TIME_INPUT_FORMAT = ['iso-8601']

TIME_INPUT_FORMAT = []



POST_SAVE_OBJ_RETURN_HOOKS = {
}

CHECK_USER_REGISTRATION = False

USER_PROFILE_MODEL_DETAILS = {
    'app': '',
    'model': '',
    'search_on_field': ''
}

USER_PROFILE_SERIALIZER = ''

DATA_RESTRICT_PERMISSIONS = {}

MASTER_FILES_MOSS_UPLOAD = False
MOSS_BASE_URL = ''
MOSS_USERNAME = ''
MOSS_PASSWORD = ''
RELATIVE_FOLDER_TO_UPLOAD_URL = ''

TRANS_FILTER_QS_SERIALIZER = {
        # 'careers.jobseeker': ('careers.trans_filter_support.return_jobseeker_qs', 'careers.trans_filter_support.JobSeekerSerializer')
}


EXCEL_IMPORT_CONFIGS = {
}


WORKFLOW_MODEL_LIST = [
]

WORKFLOW_EMAIL_CONFIGS = {
}


APPROVAL_GROUPS = [
]

GROUP_WISE_STATUS_MAPPING = {
    # 'HR': ['Pending For Approval', 'Initiated', 'Approved'],
}

EXCEL_EXPORT_CONFIGS = {}